name: applicative_validation

version: 0.0.1

description: Provides a functional domain framework for handling field and form errors.

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0
  sprintf: ^6.0.0

dev_dependencies:
  flutter_lints: 1.0.4
  test: