name: applicative_validation

version: 0.0.1

description: Provides a functional framework for handling field and form errors.

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_lints: 1.0.4
  test: